Base for new Documentation of RSI API
Akkadu/rsi-widgets pull request #25
Opened 2021-08-30 16:51 UTC by abelbordonado

## Motivation and Context
In order to work with RSI SDK Cliente, you need a way to create and handle your events without going through `akkadu.com`. Originally we will use the SDK Manager, but we have decided to provide too in first place a API (which the manager as well as the customer could use directly).

This is the `template` or `draft` of how this API documentation will be showed and explained in the docs.  Which will be updated in this PR or further for each new API integrated.

## How To Test
Check the [new section]()

## Checklist

- [x ] My code follows the code style of this project.
- [ ] I have removed all unused css, language strings, variables, functions, images and other resources.
- [ ] My change requires to update dependencies and I have updated `package.json` and `yarn.lock` accordingly.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

加油！

2021-09-07 03:56 UTC, romain130492 requested changes
alright I will have to check it again.

2021-09-07 03:56 UTC, romain130492 commented on rsi-documentation/docs/.vitepress/config.js
> +      text: 'Interpretation API',
```suggestion
      text: 'REST API',
```

2021-09-07 03:56 UTC, romain130492 commented on rsi-documentation/docs/interpreter-api/index.md
> +In order to use the Player SDK you require of a key (From your [rsi dashboard](https://rsi.akkadu.com)) and a room name from [Interpreter SDK](/interpretation-player/index.html) where you can create
```suggestion
In order to use our REST API you need to generate of a SDK key (From your [dashboard](https://rsi.akkadu.com/dashboard/events)) 
```
Why would then necessary need a roomName to use that API? since they can create a roomName here as well, that's optional

2021-09-07 03:56 UTC, romain130492 commented on rsi-documentation/docs/interpreter-api/index.md
> +In addition we provide a RSI API where you can interact directly, integrate with your platform and automatize the process.
```suggestion

```

2021-09-07 03:56 UTC, romain130492 commented on rsi-documentation/docs/interpreter-api/index.md
> +When we create a `sdk key` we require also to specify and origin. Only the origin and your localhost is whitelisted to make calls using this sdk key.
```suggestion
When using our REST API you will need to use as `origin` the one you associated with your API key. However the `localhost origin` is also whitelisted.

```

2021-09-07 03:56 UTC, romain130492 commented on rsi-documentation/docs/interpreter-api/index.md
> +In this section we will explain the different end points and how to work with them.
```suggestion
### Endpoints: 
```

2021-09-07 03:56 UTC, romain130492 commented on rsi-documentation/docs/interpreter-api/index.md
> +| POST | `/event` | [Create a Event](/interpreter-api/docs.html#create-a-event) |
```suggestion
| POST | `/event` | [Create an Event](/interpreter-api/docs.html#create-a-event) |
```

2021-09-07 03:56 UTC, romain130492 commented on rsi-documentation/docs/interpreter-api/index.md
> +| PUT | `/event` | [Update a Event](/interpreter-api/docs.html#update-an-event) |
```suggestion
| PUT | `/event` | [Update an Event](/interpreter-api/docs.html#update-an-event) |
```

2021-09-07 03:56 UTC, romain130492 commented on rsi-documentation/docs/interpreter-api/index.md
> +| DELETE | `/event` | [Delete Event](/interpreter-api/docs.html#delete-a-event) |
```suggestion
| DELETE | `/event` | [Delete an Event](/interpreter-api/docs.html#delete-a-event) |
```

2021-09-07 03:56 UTC, romain130492 commented on rsi-documentation/docs/interpreter-api/index.md
> +| GET | `/event` | [Get Event List](/interpreter-api/docs.html#get-event-list) |
```suggestion
| GET | `/event` | [Get your Events](/interpreter-api/docs.html#get-event-list) |
```

2021-09-10 04:10 UTC, deevannaveed commented on rsi-documentation/docs/interpreter-api/docs.md
> +| roomName | String | YES | Room Name to be edited | `zved` |
Room name of Event to delete

2021-09-10 04:13 UTC, deevannaveed commented on rsi-documentation/docs/interpreter-api/docs.md
> +We return the deleted event
The API will return the matched event

2021-09-10 04:37 UTC, deevannaveed commented on rsi-documentation/docs/interpreter-api/docs.md
> +All the interpretations will be done between the `Floor Language` and the `Interpreted Language`
Per language an event should have at least one interpreter and maximum 2 interpreters but normally there is a pair of two interpreters per language.
The interpreter email must be registered as interpreter at [Akkadu](https://www.akkadu.com/account/signup) before adding it to an event. All interpreter emails should be unique in an event, duplicate interpreter emails are not allowed.
`languageCode` cannot be the floor language, e.g. if an event set floor language to `en-US` then you cannot add interpreters for `en-US` using this endpoint.
All the interpretations will be done between the **Floor Language** and the **Interpreted Languages**.

2021-09-10 04:39 UTC, deevannaveed commented on rsi-documentation/docs/interpreter-api/docs.md
> +## Update Event Interpreters
It's add or update?

2021-09-10 04:41 UTC, deevannaveed commented on rsi-documentation/docs/interpreter-api/docs.md
> +| roomName | String | NO | Filter by room name | `zved` |
I think we are not filtering here but we are targeting a room so it could be "Target Event room name"?

2021-09-10 04:42 UTC, deevannaveed commented on rsi-documentation/docs/interpreter-api/docs.md
> +_1. The interpreters emails had to previously register into [Akkadu Interpreter](https://www.akkadu.com/account/signup)_
The interpreter email must be registered as interpreter at [Akkadu](https://www.akkadu.com/account/signup) before adding it to an event.

2021-09-10 04:46 UTC, deevannaveed commented on rsi-documentation/docs/interpreter-api/docs.md
> +| pair2 | String | NO | Interpreter Email<sub>1</sub> | `interpreter2@akkadu.com` |
Here this `pair1` and `pair2` is a bit confusing since its a single interpreter and they both together make a pair, better if it was `interpreter1` and `interpreter2`. But it's fine for now since that's how it is on the API.

2021-09-10 04:50 UTC, deevannaveed commented on rsi-documentation/docs/interpreter-api/docs.md
> +Delete an existing event from the interpreted languages list.
It should be remove/delete interpreters from an event?

2021-09-10 04:51 UTC, deevannaveed commented on rsi-documentation/docs/interpreter-api/docs.md
> +We return the updated language
The API will return a success response.

2021-09-10 04:56 UTC, deevannaveed commented on rsi-documentation/docs/interpreter-api/index.md
> +When using our REST API you will need to use as `origin` the one you associated with your API key. However, the `localhost origin` is also whitelisted.
To successfully call our REST API endpoints you must be using the right `origin` that you have associated with your API key. However, for development the `localhost origin` is also whitelisted.

2021-09-10 04:58 UTC, deevannaveed reviewed
@abelbordonado nice work here, I have added a few comments.

2021-09-10 09:31 UTC, abelbordonado commented on rsi-documentation/docs/interpreter-api/docs.md
> +| roomName | String | YES | Room Name to be edited | `zved` |
Lol had changed that but wasnt push. I take your message anyway

2021-09-10 09:33 UTC, abelbordonado commented on rsi-documentation/docs/interpreter-api/docs.md
> +## Update Event Interpreters
Is both

2021-09-10 09:39 UTC, abelbordonado commented on rsi-documentation/docs/interpreter-api/docs.md
> +| roomName | String | NO | Filter by room name | `zved` |
Changed in 3 places

2021-09-10 09:41 UTC, abelbordonado commented on rsi-documentation/docs/interpreter-api/docs.md
> +| pair2 | String | NO | Interpreter Email<sub>1</sub> | `interpreter2@akkadu.com` |
You read my mind xD
I think any variable end in `1` or `2` is kind of confusing. `interpreter1` is more understandable but then feels is like an array, why no `interpreter3` they will ask.  
So I hope the documents explanation make user understand what is the pair meaning (Once you get the context I think is ok)

2021-09-10 10:12 UTC, deevannaveed commented on rsi-documentation/docs/interpreter-api/docs.md
> +## Update Event Interpreters
I think then  **Add/Update Event Interpreters** is more appropriate,  **Handle Event Interpreters** will make it a bit more confusing I think.

2021-09-10 10:42 UTC, deevannaveed approved these changes
Nice work @abelbordonado  🎉

2021-09-10 10:48 UTC, merged