subtitles-feature
Akkadu/rsi-widgets pull request #30
Opened 2021-09-17 04:17 UTC by romain130492

---
name: Pull request
about: Open a new Pull Request
title: "[WIP]: "
labels: 
assignees: ''

---
Please describe the purpose of the pull request.

## Motivation and Context

## How To Test

## Screenshots (if appropriate)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have removed all unused css, language strings, variables, functions, images and other resources.
- [ ] My change requires to update dependencies and I have updated `package.json` and `yarn.lock` accordingly.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

加油！

2021-09-17 13:59 UTC, abelbordonado requested changes
Great Job! I think my comments are mostly logs and questions. I will test now. 
My only wonder is how the SDK user will enable it from the rsi dashboard. (And compute his cost)

2021-09-17 13:59 UTC, abelbordonado commented on packages/rsi-react-example/src/components/interpretation-player.jsx
> +import { RsiApiInterpretationPlayer, RsiSubtitles /* RsiApiInterpretationManager */ } from '@akkadu/rsi-react'
`/* RsiApiInterpretationManager */` Commented import

2021-09-17 13:59 UTC, abelbordonado commented on packages/rsi-subtitles/src/index.scss
> +    min-width: 100%;
Question, im not as good in css, but why here is better `min` `max` like in height and width? and not just `height` and `width`

2021-09-17 13:59 UTC, abelbordonado commented on packages/rsi-vanilla/src/rsi-subtitles.js
> +  console.log(component.dataset,'component.dataset');
🦞

2021-09-17 13:59 UTC, abelbordonado commented on packages/rsi-vanilla/update-version.js
> +console.log(process.env.AWS_ACCESS_KEY,'process.env.AWS_ACCESS_KEY,',process.env.AWS_SECRET_ACCESS_KEY,'process.env.AWS_SECRET_ACCESS_KEY');
🦞

2021-09-17 13:59 UTC, abelbordonado commented on packages/rsi-vue/src/lib-components/rsi-subtitles.vue
> +        const roomName = this.roomName ? this.roomName : this.getRoomname();
Suggest a computed value.
Or just have the if inside of getRoomname. 

```js
// First line getRoomName function
if(this.roomName) {return this.roomName; }
```

2021-09-17 13:59 UTC, abelbordonado commented on packages/rsi-vue/src/lib-components/rsi-subtitles.vue
> +      getRoomname(){
`getRoomName`

2021-09-17 13:59 UTC, abelbordonado commented on rsi-documentation/docs/subtitles/index.md
> +* The subtitles are generated by AI.
Or not, also by interpreters ok i think. All depend how they mark and how we charge them.

2021-09-17 13:59 UTC, abelbordonado commented on rsi-documentation/docs/subtitles/index.md
> +* 🚨 `RsiInterpretationPlayer` must be imported **before** `rsiSubtitles`.
Oh, thats not fun, I guess you didn't found better way

2021-09-17 14:50 UTC, abelbordonado commented
My testing results.

The credentials room `MULTI-LANGUAGE-2` is room `zjpd` no `gnma` 
Trying to interpret `gnma`  I get an error of endDate not defined. Maybe is all data, shall update the repo example roomName to the new one `zjpd`.

In Vue when I change the roomName to `zjpd` or my `noaj` I didn't get neither Audio neither subtitles. But Audio I shall be able to get

I think the subtitles are due I change the has subtitles and is not enough `true` but update the right permission from my PR [Subtitles Refactor PR](https://github.com/pulls). But audio I shall get. (Im not sure is my issue or an issue)

When I use my room Noaj I don't see the error that is not included in my SDK key.
https://deploy-preview-30--rsi-akkadu-vue-demo.netlify.app/#/interpretation-player-demo?rsi-roomname=noaj


In React one, if I try to set the `roomName`  query I get issue.
https://deploy-preview-30--rsi-akkadu-react-demo.netlify.app/interpretation-player?rsi-roomname=noaj

Lets reach on Monday and clarify here :))

2021-09-20 03:35 UTC, romain130492 commented
Just tried, It works for me, I sent you an additional video on slack to show you how we can test it

2021-09-20 03:40 UTC, romain130492 commented on packages/rsi-interpretation-player/src/index.ts
> +      throw new Error(`Unable to detect container: ${this.consumerConfig.containerSubtitles} on the DOM, please add <div id="akkadu-rsi-subtitles"/>, `)
why not, i updated that, we now give the error after 3 attempts only

2021-09-20 03:40 UTC, romain130492 commented on packages/rsi-interpretation-player/src/index.ts
> +    console.log(subtitlesTextWrapper,'subtitlesTextWrapper');
forgot that one

2021-09-20 03:41 UTC, romain130492 commented on packages/rsi-interpretation-player/src/index.ts
> +      console.log(payload, 'payload subtitles');
and that one..

2021-09-20 03:41 UTC, romain130492 commented on packages/rsi-vanilla/update-version.js
> +console.log(process.env.AWS_ACCESS_KEY,'process.env.AWS_ACCESS_KEY,',process.env.AWS_SECRET_ACCESS_KEY,'process.env.AWS_SECRET_ACCESS_KEY');
well

2021-09-20 03:42 UTC, romain130492 commented on packages/rsi-vue/src/lib-components/rsi-subtitles.vue
> +        const roomName = this.roomName ? this.roomName : this.getRoomname();
whats wrong with the current approach?

2021-09-20 03:44 UTC, romain130492 commented on packages/rsi-vue/src/lib-components/rsi-subtitles.vue
> +        const roomName = this.roomName ? this.roomName : this.getRoomname();
a computed value? this is on init, to init the sdk

2021-09-20 03:45 UTC, romain130492 commented on packages/rsi-vue/src/lib-components/rsi-subtitles.vue
> +      getRoomname(){
updated

2021-09-20 03:46 UTC, romain130492 commented on rsi-documentation/docs/subtitles/index.md
> +* The subtitles are generated by AI.
i dont get that one? I wrote you **can**

2021-09-20 03:46 UTC, romain130492 commented on rsi-documentation/docs/subtitles/index.md
> +* 🚨 `RsiInterpretationPlayer` must be imported **before** `rsiSubtitles`.
yep thats not fun, its just temporary

2021-09-20 03:48 UTC, romain130492 commented on packages/rsi-interpretation-player/src/index.ts
> +    config: { apiKey: string, roomName: string, hasSubtitles:string, container:string, placeholderText:string, isPlayerControlled:boolean, displayFlag:boolean },
I'm not sure which version you got here, `hasSubtitles` is already in the current version

2021-09-20 03:49 UTC, romain130492 commented on packages/rsi-interpretation-player/src/index.ts
> +          if (!this.selectedLanguageUI) {
`Check this file self note` ? what's the meaning of that?

2021-09-20 10:30 UTC, abelbordonado commented on packages/rsi-interpretation-player/src/index.ts
> +    config: { apiKey: string, roomName: string, hasSubtitles:string, container:string, placeholderText:string, isPlayerControlled:boolean, displayFlag:boolean },
Yes, I think I panic cos thats not related server side

2021-09-20 10:31 UTC, abelbordonado commented on packages/rsi-interpretation-player/src/index.ts
> +          if (!this.selectedLanguageUI) {
My own self note. but I did verify in detail the file and was ok

2021-09-20 10:34 UTC, abelbordonado commented on rsi-documentation/docs/subtitles/index.md
> +* The subtitles are generated by AI.
`* The subtitles are generated by AI.`  not only by AI, but also by interpreters.  I meant the second line

2021-09-20 13:41 UTC, abelbordonado commented on packages/rsi-vue/src/lib-components/rsi-subtitles.vue
> +        const roomName = this.roomName ? this.roomName : this.getRoomname();
```js
{
  computed:{
       getRoomName() { this.roomName ? this.roomName : this.getRoomname() } 
  }
} 
```

Yes, computed, Naveed suggested me the same. No matter if not.
But my question now is, what happen if they change the attribute dynamically?

2021-09-20 13:57 UTC, abelbordonado commented on packages/rsi-interpretation-player/src/index.ts
> +   * @description If hasSubtitles is True, we handle the subtitles for this event.
no need

2021-09-20 14:14 UTC, romain130492 commented on rsi-documentation/docs/subtitles/index.md
> +* The subtitles are generated by AI.
```suggestion
* The subtitles are generated by AI or by your interpreter.
```

2021-09-20 14:15 UTC, romain130492 commented on rsi-documentation/docs/subtitles/index.md
> +* The subtitles are generated by AI.
right, updated

2021-09-20 14:18 UTC, romain130492 commented on packages/rsi-interpretation-player/src/index.ts
> +  handleTextSubtitles ({ sentence, status }, textRecognized, textRecognizing, subtitlesTextWrapper) {
ok

2021-09-20 14:19 UTC, romain130492 commented on packages/rsi-subtitles/src/index.scss
> +    min-width: 100%;
min-width is something like it can be less that `number`, width fix the thing to a certain value?

2021-09-20 14:20 UTC, romain130492 commented on packages/rsi-vanilla/src/interpretation-player.js
>    console.log(component.dataset,'component.dataset');
```suggestion

```

2021-09-20 14:21 UTC, abelbordonado commented on packages/rsi-subtitles/src/index.scss
> +    min-width: 100%;
Oh I know that, but why wouldn't just use `width: 100%` instead of `min-width: 100%, max-width: 100%`

2021-09-20 14:22 UTC, romain130492 commented on packages/rsi-react-example/src/components/interpretation-player.jsx
> +import { RsiApiInterpretationPlayer, RsiSubtitles /* RsiApiInterpretationManager */ } from '@akkadu/rsi-react'
```suggestion
import { RsiApiInterpretationPlayer, RsiSubtitles  } from '@akkadu/rsi-react'
```

2021-09-20 14:24 UTC, romain130492 commented on packages/rsi-subtitles/src/index.scss
> +    min-width: 100%;
```suggestion
    width: 100%;
```

2021-09-20 14:27 UTC, romain130492 commented on packages/rsi-vanilla/src/rsi-subtitles.js
> +  console.log(component.dataset,'component.dataset');
```suggestion

```

2021-09-20 15:07 UTC, abelbordonado approved these changes
Great job! All comments resolved and seems to work with no problem.

2021-09-20 15:26 UTC, merged