Feat/18n property
Akkadu/rsi-widgets pull request #40
Opened 2021-11-04 11:17 UTC by abelbordonado

## Motivation and Context
Our RSI widget is for interpretation purpose, but the labels we display on it are always in English! 

This proposal exposes and attributes `i18n` for the developer to inject their own customized translations/labels per language.

**Other Changes**
- `muted`: We have also wired the `muted` prop with no logic yet
-  React Example we have separate the state from the props. 
- ⚠️ Except the new attributes, other attributes are not reactive! If the attribute content changes after initialization wont have effect.

## How To Test

I have no test in the demo page, but in the mini-demo contain inside each repo.

- RSI Vue 
- RSI React
![image](https://user-images.githubusercontent.com/37141039/140304378-c702df2b-246f-41fb-89aa-90ca70a255a9.png)

In the demo we have exposed three languages with a set of specific options (Chinese, English, Spanish, Japanese, Korean, French, Hindu). Clicking in the radio button shall modify the labels and the selected label also.
- RSI Vanilla
![image](https://user-images.githubusercontent.com/37141039/140303499-b97cba04-c106-406e-8a5c-7752d56e419b.png)

In the demo we have exposed three languages with a set of specific options (Chinese, English, Spanish, Japanese, Korean, French, Hindu). Clicking in the radio button shall modify the labels and the selected label also.

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have removed all unused css, language strings, variables, functions, images and other resources.
- [ ] My change requires to update dependencies and I have updated `package.json` and `yarn.lock` accordingly.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

加油！

2021-11-05 06:44 UTC, romain130492 commented on packages/rsi-interpretation-player/src/index.ts
> +    return `https://www.countryflags.io/${iso}/flat/64.png`;
why are we removing our flags ?
Naveed added theses flags because their API was down.

2021-11-05 06:46 UTC, romain130492 commented on packages/rsi-react/example/src/App.js
> +  'zh': {
i Thing we are covering more languages than that no?

2021-11-05 06:47 UTC, romain130492 commented on packages/rsi-vanilla/demo/i18n-example.js
> +    "en": "英文",
same here

2021-11-05 06:48 UTC, romain130492 commented on packages/rsi-vanilla/demo/i18n-example.js
> +    "en": "英文",
why dont we add that file in the interpretation-player. then every packages could access to it

2021-11-05 06:49 UTC, romain130492 commented on packages/rsi-vanilla/src/interpretation-player.js
> +console.log({ config, 'a': 2 })
log

2021-11-05 06:51 UTC, romain130492 requested changes
I didnt test the functionnalities yet, but I added a few comments

2021-11-05 09:06 UTC, abelbordonado commented on packages/rsi-interpretation-player/src/index.ts
> +    return `https://www.countryflags.io/${iso}/flat/64.png`;
![image](https://user-images.githubusercontent.com/37141039/140485568-18b36371-704d-45b8-a78f-7f94637f5916.png)
Hadn't removed the flags, and Evil 👿 merge had to remove it. I add them back but the last commit fails to upload sorry.

2021-11-05 09:07 UTC, abelbordonado commented on packages/rsi-react/example/src/App.js
> +  'zh': {
This is just an example to test the idea.  Based on the example room. The real input will come from the developer

2021-11-05 09:07 UTC, abelbordonado commented on packages/rsi-vanilla/demo/i18n-example.js
> +    "en": "英文",
The same is just an example. Developer will input their names as their own needs

2021-11-05 09:08 UTC, abelbordonado commented on packages/rsi-vanilla/src/interpretation-player.js
> +console.log({ config, 'a': 2 })
🦞

2021-11-08 05:38 UTC, romain130492 commented on packages/rsi-interpretation-player/src/index.ts
> +    return `https://www.countryflags.io/${iso}/flat/64.png`;
i mean can you reset it to the right thing?
I still can see the wrong line being used
``` const iso = code.slice(-2);
    return `https://www.countryflags.io/${iso}/flat/64.png`;
```

2021-11-08 05:41 UTC, romain130492 commented on packages/rsi-interpretation-player/src/index.ts
> +    return `https://www.countryflags.io/${iso}/flat/64.png`;
<img width="572" alt="Screen Shot 2021-11-08 at 1 40 34 PM" src="https://user-images.githubusercontent.com/57079606/140689991-ed3961ae-ded1-45df-80c5-5e726f9bc36d.png">
怎么办？

2021-11-08 05:48 UTC, romain130492 commented on packages/rsi-react/example/src/App.js
> +    <div onChange={(e) => setLangauge(e.target.value)}>
typo

2021-11-08 05:49 UTC, romain130492 commented on packages/rsi-react/example/src/App.js
> +  const [language, setLangauge] = useState('en')
typo

2021-11-08 05:49 UTC, romain130492 commented on packages/rsi-react/example/src/App.js
> +    <div onChange={(e) => setLangauge(e.target.value)}>
lets add a simple padding-top of 3rem?

2021-11-08 05:53 UTC, romain130492 commented on packages/rsi-vanilla/interpretation-player.html
> +  <div id="akkadu-rsi-subtitles" data-sdk-key="8abec1e6-844e-4881-afc5-1513479c8532" data-room-name="gnng"></div>
```suggestion
  <div id="akkadu-rsi-subtitles" data-sdk-key="8abec1e6-844e-4881-afc5-1513479c8532" data-room-name="gnma"></div>
```

2021-11-08 05:54 UTC, romain130492 commented on packages/rsi-vanilla/interpretation-player.html
> +  <div id="akkadu-interpretation-player" data-sdk-key="92ea1a19-5846-4729-9706-7cdfbfdef9d4" data-position-menu="bottom"
```suggestion
  <div id="akkadu-interpretation-player" data-sdk-key="8abec1e6-844e-4881-afc5-1513479c8532"  data-position-menu="bottom"
```

2021-11-08 05:54 UTC, romain130492 commented on packages/rsi-vanilla/interpretation-player.html
> +    data-room-name="gnng" data-has-subtitles="true" data-is-box-shadow="true" data-is-player-controlled="true"
```suggestion
    data-room-name="gnma" data-has-subtitles="true" data-is-box-shadow="true" data-is-player-controlled="true"
```

2021-11-08 05:58 UTC, romain130492 requested changes
Hey
The functionalities work well for me, except well the flag, I'm not sure why that line was updated.
I think we should also ask Alvaro to test using the preview once you release the packages.

2021-11-08 10:00 UTC, abelbordonado commented on packages/rsi-react/example/src/App.js
> +    <div onChange={(e) => setLangauge(e.target.value)}>
🦞

2021-11-09 10:44 UTC, romain130492 approved these changes

2021-11-16 07:49 UTC, romain130492 approved these changes
great !

2021-11-16 07:52 UTC, merged